// Code generated by spec-first example; DO NOT EDIT.
package main

import (
	"net/http"

	"github.com/aatuh/api-toolkit/contrib/v4/contracts"
	"github.com/aatuh/api-toolkit/v4/fielderrors"
)

const (
	CreatePetMethod = http.MethodPost
	CreatePetPath   = "/pets"
	ListPetsMethod  = http.MethodGet
	ListPetsPath    = "/pets"
)

type Handlers interface {
	CreatePet(http.ResponseWriter, *http.Request)
	ListPets(http.ResponseWriter, *http.Request)
}

func RegisterRoutes(r contracts.HTTPRouter, h Handlers) {
	if r == nil || h == nil {
		return
	}
	r.Post(CreatePetPath, h.CreatePet)
	r.Get(ListPetsPath, h.ListPets)
}

type StatusError interface {
	error
	StatusCode() int
}

type CreatePetBadRequest struct {
	Detail string
	Errors fielderrors.FieldErrors
}

func (e CreatePetBadRequest) Error() string   { return e.Detail }
func (e CreatePetBadRequest) StatusCode() int { return http.StatusBadRequest }

func (e CreatePetBadRequest) FieldErrors() fielderrors.FieldErrors { return e.Errors }

type CreatePetConflict struct {
	Detail string
	Errors fielderrors.FieldErrors
}

func (e CreatePetConflict) Error() string   { return e.Detail }
func (e CreatePetConflict) StatusCode() int { return http.StatusConflict }

func (e CreatePetConflict) FieldErrors() fielderrors.FieldErrors { return e.Errors }

type ListPetsBadRequest struct {
	Detail string
	Errors fielderrors.FieldErrors
}

func (e ListPetsBadRequest) Error() string   { return e.Detail }
func (e ListPetsBadRequest) StatusCode() int { return http.StatusBadRequest }

func (e ListPetsBadRequest) FieldErrors() fielderrors.FieldErrors { return e.Errors }
