package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type packageClass struct {
	ImportPath string
	APIStatus  string
}

type symbol struct {
	Name        string
	Kind        string
	Added       string
	Deprecation string
}

func main() {
	root := flag.String("root", ".", "repository root")
	classification := flag.String("classification", "docs/package-classification.tsv", "package classification TSV")
	out := flag.String("out", "docs/api-inventory.md", "output Markdown path")
	flag.Parse()

	if err := run(*root, *classification, *out); err != nil {
		fmt.Fprintln(os.Stderr, "apiinventory:", err)
		os.Exit(1)
	}
}

func run(root, classificationPath, outPath string) error {
	root = filepath.Clean(root)
	modulePath, err := modulePath(filepath.Join(root, "go.mod"))
	if err != nil {
		return err
	}
	classes, err := readPackageClasses(filepath.Join(root, classificationPath), modulePath)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "# Public API Inventory")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "<!-- Code generated by internal/tools/apiinventory; DO NOT EDIT. -->")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "This inventory is generated from `docs/package-classification.tsv` and")
	fmt.Fprintln(&buf, "non-test Go source files for root packages classified as `stable` or")
	fmt.Fprintln(&buf, "`compatibility-only`.")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "Added version currently records the v3 compatibility surface, not the")
	fmt.Fprintln(&buf, "original historical commit for each symbol. Use release notes for finer")
	fmt.Fprintln(&buf, "history when a symbol was added after the v3 baseline.")
	fmt.Fprintln(&buf)

	for _, cls := range classes {
		rel := strings.TrimPrefix(cls.ImportPath, modulePath)
		rel = strings.TrimPrefix(rel, "/")
		dir := filepath.Join(root, filepath.FromSlash(rel))
		symbols, err := packageSymbols(dir)
		if err != nil {
			return fmt.Errorf("%s: %w", cls.ImportPath, err)
		}
		fmt.Fprintf(&buf, "## `%s`\n\n", cls.ImportPath)
		fmt.Fprintf(&buf, "Stability tier: `%s`\n\n", cls.APIStatus)
		if len(symbols) == 0 {
			fmt.Fprintln(&buf, "No exported symbols detected.")
			fmt.Fprintln(&buf)
			continue
		}
		fmt.Fprintln(&buf, "| Symbol | Kind | Added version | Deprecation status |")
		fmt.Fprintln(&buf, "| --- | --- | --- | --- |")
		for _, sym := range symbols {
			fmt.Fprintf(&buf, "| `%s` | %s | %s | %s |\n", sym.Name, sym.Kind, sym.Added, sym.Deprecation)
		}
		fmt.Fprintln(&buf)
	}

	outputPath := outPath
	if !filepath.IsAbs(outputPath) {
		outputPath = filepath.Join(root, outputPath)
	}
	outBytes := bytes.TrimRight(buf.Bytes(), "\n")
	outBytes = append(outBytes, '\n')
	if err := os.WriteFile(outputPath, outBytes, 0o644); err != nil {
		return fmt.Errorf("write inventory: %w", err)
	}
	return nil
}

func modulePath(goMod string) (string, error) {
	file, err := os.Open(goMod)
	if err != nil {
		return "", fmt.Errorf("read go.mod: %w", err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) == 2 && fields[0] == "module" {
			return fields[1], nil
		}
	}
	if err := scanner.Err(); err != nil {
		return "", fmt.Errorf("scan go.mod: %w", err)
	}
	return "", fmt.Errorf("module directive not found in %s", goMod)
}

func readPackageClasses(path, modulePath string) ([]packageClass, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("read package classification: %w", err)
	}
	defer file.Close()

	var classes []packageClass
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		cols := strings.Split(line, "\t")
		if len(cols) < 2 {
			continue
		}
		importPath := cols[0]
		status := cols[1]
		if !strings.HasPrefix(importPath, modulePath) {
			continue
		}
		if status != "stable" && status != "compatibility-only" {
			continue
		}
		classes = append(classes, packageClass{ImportPath: importPath, APIStatus: status})
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scan package classification: %w", err)
	}
	sort.Slice(classes, func(i, j int) bool { return classes[i].ImportPath < classes[j].ImportPath })
	return classes, nil
}

func packageSymbols(dir string) ([]symbol, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(info os.FileInfo) bool {
		name := info.Name()
		return strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go")
	}, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	if len(pkgs) == 0 {
		return nil, fmt.Errorf("no Go package found")
	}

	var syms []symbol
	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				switch decl := decl.(type) {
				case *ast.GenDecl:
					syms = append(syms, genDeclSymbols(decl)...)
				case *ast.FuncDecl:
					if decl.Name == nil || !decl.Name.IsExported() {
						continue
					}
					name := decl.Name.Name
					kind := "func"
					if decl.Recv != nil && len(decl.Recv.List) > 0 {
						recv := receiverName(decl.Recv.List[0].Type)
						if recv == "" || !ast.IsExported(recv) {
							continue
						}
						name = recv + "." + decl.Name.Name
						kind = "method"
					}
					syms = append(syms, newSymbol(name, kind, docText(decl.Doc)))
				}
			}
		}
		break
	}

	sort.Slice(syms, func(i, j int) bool {
		if syms[i].Name == syms[j].Name {
			return syms[i].Kind < syms[j].Kind
		}
		return syms[i].Name < syms[j].Name
	})
	return syms, nil
}

func genDeclSymbols(decl *ast.GenDecl) []symbol {
	var syms []symbol
	for _, spec := range decl.Specs {
		switch spec := spec.(type) {
		case *ast.TypeSpec:
			if spec.Name == nil || !spec.Name.IsExported() {
				continue
			}
			doc := docText(spec.Doc)
			if doc == "" {
				doc = docText(decl.Doc)
			}
			typeName := spec.Name.Name
			syms = append(syms, newSymbol(typeName, "type", doc))
			syms = append(syms, typeMemberSymbols(typeName, spec.Type)...)
		case *ast.ValueSpec:
			doc := docText(spec.Doc)
			if doc == "" {
				doc = docText(decl.Doc)
			}
			kind := strings.ToLower(decl.Tok.String())
			for _, name := range spec.Names {
				if name == nil || !name.IsExported() {
					continue
				}
				syms = append(syms, newSymbol(name.Name, kind, doc))
			}
		}
	}
	return syms
}

func typeMemberSymbols(typeName string, expr ast.Expr) []symbol {
	var syms []symbol
	switch typ := expr.(type) {
	case *ast.StructType:
		if typ.Fields == nil {
			return nil
		}
		for _, field := range typ.Fields.List {
			doc := docText(field.Doc)
			if doc == "" {
				doc = docText(field.Comment)
			}
			for _, name := range exportedFieldNames(field) {
				syms = append(syms, newSymbol(typeName+"."+name, "field", doc))
			}
		}
	case *ast.InterfaceType:
		if typ.Methods == nil {
			return nil
		}
		for _, method := range typ.Methods.List {
			doc := docText(method.Doc)
			if doc == "" {
				doc = docText(method.Comment)
			}
			for _, name := range exportedFieldNames(method) {
				syms = append(syms, newSymbol(typeName+"."+name, "interface method", doc))
			}
		}
	}
	return syms
}

func exportedFieldNames(field *ast.Field) []string {
	if len(field.Names) == 0 {
		name := exprName(field.Type)
		if name != "" && ast.IsExported(name) {
			return []string{name}
		}
		return nil
	}
	var names []string
	for _, name := range field.Names {
		if name != nil && name.IsExported() {
			names = append(names, name.Name)
		}
	}
	return names
}

func receiverName(expr ast.Expr) string {
	if star, ok := expr.(*ast.StarExpr); ok {
		return exprName(star.X)
	}
	return exprName(expr)
}

func exprName(expr ast.Expr) string {
	switch expr := expr.(type) {
	case *ast.Ident:
		return expr.Name
	case *ast.SelectorExpr:
		return expr.Sel.Name
	case *ast.IndexExpr:
		return exprName(expr.X)
	case *ast.IndexListExpr:
		return exprName(expr.X)
	}
	return ""
}

func newSymbol(name, kind, doc string) symbol {
	deprecation := "active"
	if strings.Contains(doc, "Deprecated:") {
		deprecation = "deprecated"
	}
	return symbol{
		Name:        name,
		Kind:        kind,
		Added:       "v3 compatibility surface",
		Deprecation: deprecation,
	}
}

func docText(group *ast.CommentGroup) string {
	if group == nil {
		return ""
	}
	return group.Text()
}
